### PR TITLE
Add draft test suites

### PR DESCRIPTION
**Pull request by bloodeagle40234**
This PR initialize the test suites for the lfsccm python package.

bonus, change the lfsccm exit strategy to use native python console script logic. in the console script installation, what we should do is just return the integer exit code, then the script will exit with the code.

### CODE REVIEW

**Comment by kaneko-tx** [comment]
I think it is mostly good.
However, when I ran test suites, I got a `ModuleNotFoundError: No module named 'mock'`.

`pip install mock` solves the problem, so how about either of the following modifications?
- Add `mock` to `test-requirements.txt`.
- Use `unittest.mock` instead of `mock`.

**Comment by bloodeagle40234** [comment]
Good catch @kaneko-tx 
From the docs(*1), the unittest seems better because it has been the standard library on python3 since py3.3(*2). And the mock package on pypi is just the backport. I'll fix it in the following commits in this branch. Thanks.

1. https://pypi.org/project/mock/
2. https://docs.python.org/dev/library/unittest.mock.html

**Review by rkmrHonjo — CHANGES_REQUESTED** [review]
Hi @bloodeagle40234  ,

Commits look good to me.

But, I have one request. Could you please add documentation on how to run the tests?

**Comment by kaneko-tx** [comment]
Thank you for your commit https://github.com/DDNStorage/lfsccm/pull/3/commits/1aed68e7199cfa102573b7bfad105d81206cbabb.
Looks good to me.

**Comment by bloodeagle40234** [comment]
> Hi @bloodeagle40234 ,
> 
> Commits look good to me.
> 
> But, I have one request. Could you please add documentation on how to run the tests?

Can I make the docs and github actions template for your request in another PR later because this PR is intended to discuss the test format (e.g. the test framework, directory structure).

I'm planning to push more commits to prepare concrete testing environment we can use somewhere.

**Review by rkmrHonjo — APPROVED** [review]
@bloodeagle40234 
OK, I understand your plan. I approve this PR.

**Pull request merged**
